import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import {
  ApolloClient,
  InMemoryCache,
  ApolloProvider,
  gql,
} from "@apollo/client";
import Posts from "../components/posts";

const client = new ApolloClient({
  uri: "https://api-us-west-2.hygraph.com/v2/cl8k1zu6q18pe01td4a3pduq9/master",
  cache: new InMemoryCache(),
});

const queryBlogs = gql`
  query Blogs {
    blogs {
      publishedAt
      datePublished
      id
      publishedAt
      slug
      title
      updatedAt
      content {
        html
      }
      author {
        name
        avatar {
          url
        }
      }
      coverPhoto {
        url
      }
    }
  }
`;

export async function getStaticProps() {
  const posts = await client.query({
    query: queryBlogs,
  });

  return {
    props: {
      posts,
    },
    revalidate: 10,
  };
}

export default function Home({ posts }) {
  console.log(posts, "posts");
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <h1>List of Blogs</h1>
        {posts?.data?.blogs?.map((item) => (
          <Posts item={item} />
        ))}
      </main>
    </div>
  );
}
